### ISSUE TITLE
Опечатка в переменной

### ISSUE THREAD

**Issue by pavluk** [AlekVolsk/mod_uk_tabs#1]
https://github.com/AlekVolsk/mod_uk_tabs/blob/master/mod_uk_tabs.php#L17
Опечатка в переменной "$$" заменить на "$"

**Comment by AlekVolsk** [comment]
нет, это не опечатка, это обращение к динамической переменной

```php
$var = 'tabs_class';
$$var = '123';
```

в итоге получим переменную с именем `$tabs_class` со значением '123'
